james = User.create(name: 'james', username: 'jamesdesousa', password: 'james123')
edm = Genre.create(genreName: 'Electronic')
pop = Genre.create(genreName: 'Pop')
rock= Genre.create(genreName: 'Rock')
awaken = Song.create(name: 'Awaken', artist: 'Big Wild', track_id: '4oYzwOTWpP3JTyKrTHJtqw', genre_id: 1)
gravity = Song.create(name: 'Gravity', artist: 'John Mayer', track_id: '3SktMqZmo3M9zbB7oKMIF7', genre_id: 2 )
wildflowers = Song.create(name: 'Wildflowers', artist: 'Tom Petty', track_id: "2Pr1nZpt8A8WP7QYpyq6L3", genre_id: 3)
post3 = Post.create(song_id: 3, user_id: 1)
post2 = Post.create(song_id: 2, user_id: 1)
post1 = Post.create(song_id: 1, user_id: 1)
puts ('done!')